### ISSUE TITLE
Provide URL for article page without the header

### ISSUE THREAD

**Issue by BlueReZZ** [elifesciences/enhanced-preprints#105]
We're exploring how enhanced preprints could be integrated into PubPub  - an open-source and hosted publishing system developed by the Knowledge Futures Group.

They could offer CMS capabilities for people like Biophysics Colab who want to show selected enhanced preprints on their own website and in collections/editorials etc. and are looking at changing their article or 'pub' to become a container for content rather than the content itself. You can currently import directly into their system using JATS or Word etc. but we want to have control over the rendering of the HTML and CSS.

They plan to prototype this by using an iframe before exploring a better solution for embedding so asked if we could provide a URL to the EPP prototype content that didn't render the header. Something like a querystring parameter or a different route would suffice.

**Comment by Maelplaine** [comment]
Currently, the header is very simple. (see screenshot)

![Image](https://user-images.githubusercontent.com/39725642/173795725-481ee3b0-088c-4e56-9df6-c528930ff1f9.png)

Will says it should be quick

**Comment by scottaubrey** [comment]
`?noHeader=true` to article or review page
