### ISSUE TITLE
Style "Back to article" button on Reviews page

### ISSUE THREAD

**Issue by Maelplaine** [elifesciences/enhanced-preprints#117]

**Comment by nlisgo** [comment]
@Maelplaine @chris-huggins could you drop in a link to the design please?

Is there a hover state? Are there other buttons in use that are styled the same way?

**Comment by chris-huggins** [comment]
https://projects.invisionapp.com/d/main#/console/22030924/467140917/inspect

The button style should be the same as download, cite etc. on the article page.

It doesn't appear to have a hover style yet. Please just make the fill #D7D9DE on hover for the back to article as well as download etc. buttons.

**Comment by chris-huggins** [comment]
If you're working on the responsive behaviour at all, the back to article button should be above the page title etc. at the top of the page, when the layout goes down to a single column. I can help on this if needed.

**Comment by nlisgo** [comment]
None of the articles are presenting the reviews yet, unless I'm mistaken.

> the back to article button should be above the page title

We should address this as a follow up when we present the title and reviews successful on this page.
