### ISSUE TITLE
Add MSA label(s) above the article title (Harcoded)

### ISSUE THREAD

**Issue by Maelplaine** [elifesciences/enhanced-preprints#134]
We should style them the same as they are on the journal

![Image](https://user-images.githubusercontent.com/39725642/174997571-57e8e61c-ae22-42d7-a3f6-a71332fbe398.png)

**Comment by will-byrne** [comment]
@Maelplaine @chris-huggins 
The designs are quite different to the journal, is this deliberate and which should we implement?

**Comment by chris-huggins** [comment]
@Maelplaine Are you ok for them to be styled to match the designs? 

<img width="823" alt="image" src="https://user-images.githubusercontent.com/41907215/183428410-566d25fe-ee5d-4a69-af78-2ba381ff4381.png">

**Comment by Maelplaine** [comment]
@chris-huggins  Yes I think it's fine
