### ISSUE TITLE
Reduce space between top of the page and jump-to-menu and secondary column 

### ISSUE THREAD

**Issue by Maelplaine** [elifesciences/enhanced-preprints#152]
# Description

Reduce space between top of the page and jump-to-menu and secondary column

# Subtasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

# Definition of Done

- [ ] Item 1
- [ ] Item 2
- [ ] ...

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/39725642/176402479-a5218a87-be1d-427b-b714-e062a486bc3d.png">

**Comment by discodavey** [comment]
@chris-huggins What height do you want this reduced to?

**Comment by chris-huggins** [comment]
@discodavey They should both be 96px. Thanks.
