### ISSUE TITLE
Setup hosting for user experience HTML examples and setup url

### ISSUE THREAD

**Issue by discodavey** [elifesciences/enhanced-preprints#177]
# Description

Setup hosting for user experience html examples and setup url

# Subtasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

# Definition of Done

- [ ] Item 1
- [ ] Item 2
- [ ] ...

**Comment by chris-huggins** [comment]
github pages are fine. Whatever's easiest/quickest. I will need to include a link to each version in a survey but it doesn't matter what the URL is.

**Comment by discodavey** [comment]
@chris-huggins Which article are we using?

**Comment by chris-huggins** [comment]
https://elifesciences.org/articles/57443

I can supply the text for the summary for this article, although I think it might already be in the EPP prototype.

**Comment by chris-huggins** [comment]
We can just cut off some author names instead of including the full list with expand/collapse

**Comment by discodavey** [comment]
I thought we were lifting the content from one of the demo's we already had?

**Comment by chris-huggins** [comment]
We can do if it's quicker, but the summary Mike provided relates to this paper. Apologies I thought we had worked on that one already. 

I see a version on the EPP already (https://epp-node-prototype.elifesciences.org/article/10.1101/2020.04.07.030213)
Is that from this morning?

**Comment by discodavey** [comment]
Yes. @scottaubrey did this

**Comment by chris-huggins** [comment]
Are you ok to continue with that article in that case? Hopefully we can find a quick way to represent the tables. They don't need to be responsive.
