### ISSUE TITLE
Create an initial design for the article view

### ISSUE THREAD

**Issue by NuclearRedeye** [elifesciences/enhanced-preprints#19]
# Description

We need to get an initial design that shows that the article view will look like for an enhanced preprint.

# DoD
- [ ] An initial design, reviewed and approved by stakeholders shared with engineering ready to be implemented.

**Comment by chris-huggins** [comment]
Current designs are here. I've invited Will and Scott to the InVision project so they can use "Inspect" if they like. When I get a chance I'll work on providing some more guidance on responsive behaviour.

https://invis.io/BY12H1HZSGTQ#/464953978_elife-Reviewed

**Comment by chris-huggins** [comment]
Colab version: https://invis.io/BY12H1HZSGTQ#/464953979_colab-Endorsed

**Comment by scottaubrey** [comment]
Closing this issue - further refinement of the current prototype layout can and should be done via backlog items
