### ISSUE TITLE
Configure repository to prevent merges without ci passing and peer review

### ISSUE THREAD

**Issue by NuclearRedeye** [elifesciences/enhanced-preprints#30]
# DoD
- [x] Can't push directly to the master/main branch.
- [x] Setup team access to the repository.
- [x] Add branch protection rules to enforce that CI is passing and code has at least 1 review before allowing for merge

**Comment by scottaubrey** [comment]
My suggested setup for Will to review
<img width="780" alt="Screenshot 2022-04-07 at 10 24 31 am" src="https://user-images.githubusercontent.com/375812/162167204-d828a2f9-2822-4e9f-98d3-2ccee7ffc179.png">


Requires https://github.com/elifesciences/enhanced-preprints/pull/36 and https://github.com/elifesciences/enhanced-preprints/pull/35 to be merged first.
