### ISSUE TITLE
Would 'Article Hosting' be a suitable solution for the first iteration?

### ISSUE THREAD

**Issue by NuclearRedeye** [elifesciences/enhanced-preprints#5]
# Description

Look at the existing https://article.hosting system to see if it could be reused.

# DoD
- [ ] A decision on if it is worth reusing any of the article.hosting solution.
- [ ] List of options updated.

**Comment by scottaubrey** [comment]
My notes from looking into article hosting:
- It took a little while to get enough moving parts working to get off the ground. Not insurmountable, but effort to essentially stand still.
- The overall project structure is relatively complex (dare I say, over-engineered?) for what we're wanting to start with. 
- The core of the importer is built around stencila/encoda to convert an XML article to JSON, and maybe that would be a better base to build from (see #4)

**Comment by will-byrne** [comment]
Having investigated the code, this solution is too over engineered to do what we want it to do.
There are also some red flags given the time and complexity to get it to run.
It is probable the time required to get it to be of use is prohibitive.
