### ISSUE TITLE
Does Sciety have an API that can be used to get review data for a specific article?

### ISSUE THREAD

**Issue by NuclearRedeye** [elifesciences/enhanced-preprints#8]
# Description

We need to display review data with the article data, and as such we need to get that review data from somewhere. Sciety we think should be able to get this data for us, hence we need to investigate the API's they have (if any) and see if they can supply the information that we need.

# DoD
- [x] An answer to the question 'can we use Sciety's API to get review information for a specific article'.
- [x] Understand if we can also get the review data itself from sciety.org, and if not where we need to get it from.
- [x] Next steps, raised as issues in the backlog.

**Comment by NuclearRedeye** [comment]
It does, here is [an example](https://sciety.org/docmaps/v1/articles/10.1101/2021.08.06.21261725.docmap.json) that gets some review information for a specific article.

**Comment by NuclearRedeye** [comment]
Following on from my above message, I've just spent some time watching the background video [here](https://docmaps.knowledgefutures.org/) which gives some more context around the structure of the response from the API. Would advise you both watch it also.

**Comment by NuclearRedeye** [comment]
Also need to figure out how we get actual review content

**Comment by will-byrne** [comment]
For Biophysics Colab we can get the review content via the `hypothesis` api which returns a `JSON` object containing the content of the review and some related data.

for example: [a review from our sample paper](https://api.hypothes.is/api/annotations/A2ZbGBCxEeyu-CsIpygfMQ)

This is probably enough for us to get started without worrying about duplicating effort from Sciety as its only a single call and a type to match the `JSON` output.

If we combine the two calls to `docmaps` and `hypothesis` we will have all of the meta information and the content of the review. We will need to speak to the Sciety team about when they will add the Biophysics Colab group to the available docmaps.

**Comment by will-byrne** [comment]
I have spoken to a member of the Sciety team and while adding other groups to the `docmaps` api is on the cards its not an immediate priority so it may be best (as they suggested) to hardcode a response of the `docmap` call in the code so we can just swap in the fetch when that has been done and still get on with the rest of the tasks.
